#!/bin/bash
# Project Cleanup Script - Remove Unnecessary Files
# Keeps only essential files for hackathon submission

set -e

echo "=========================================="
echo "Project Cleanup - Removing Unnecessary Files"
echo "=========================================="
echo ""

# Create backup directory
BACKUP_DIR="./cleanup_backup_$(date +%Y%m%d_%H%M%S)"
mkdir -p "$BACKUP_DIR"
echo "✅ Created backup directory: $BACKUP_DIR"
echo ""

# Function to safely delete files
safe_delete() {
    local file="$1"
    if [ -f "$file" ]; then
        cp "$file" "$BACKUP_DIR/"
        rm "$file"
        echo "  ✓ Deleted: $file"
    fi
}

echo "🗑️  Removing demo and test Python files..."
safe_delete "./demo_clean.py"
safe_delete "./demo_complete.py"
safe_delete "./demo_complete_system.py"
safe_delete "./demo_final.py"
safe_delete "./demo_live.py"
safe_delete "./demo_live_system.py"
safe_delete "./demo_working.py"
safe_delete "./hackathon_demo.py"
safe_delete "./interactive_demo.py"
safe_delete "./production_demo.py"
safe_delete "./simple_demo.py"
safe_delete "./quick_categorize_expense.py"
safe_delete "./quick_optimize_content.py"
safe_delete "./quick_route_task.py"
safe_delete "./quick_system_health.py"
safe_delete "./test_automation_systems.py"
safe_delete "./test_deployed_system.py"
safe_delete "./test_filesystem_watcher.py"
safe_delete "./test_learning_systems.py"
safe_delete "./test_multi_agent_system.py"
safe_delete "./test_platinum_integration.py"
safe_delete "./test_twitter_api.py"
safe_delete "./batch_process_expenses.py"
echo ""

echo "🗑️  Removing unnecessary shell scripts..."
safe_delete "./ralph_setup.sh"
safe_delete "./ralph_wiggum_setup.sh"
safe_delete "./run_ralph_tests.sh"
safe_delete "./setup_ralph_tests.sh"
safe_delete "./test_ralph_simple.sh"
safe_delete "./test_ralph_groq.sh"
safe_delete "./test_full_system.sh"
safe_delete "./test_interactive.sh"
safe_delete "./test_odoo_integration.sh"
safe_delete "./start_automation_mcp.sh"
safe_delete "./start_health_monitor.sh"
safe_delete "./start_multi_agent_mcp.sh"
safe_delete "./verify_gold_tier_deployment.sh"
safe_delete "./run_all_tests.sh"
safe_delete "./deploy_platinum_tier.sh"
echo ""

echo "🗑️  Removing status and summary markdown files..."
safe_delete "./ALL_ISSUES_RESOLVED.md"
safe_delete "./AUDIT_LOGGING_IMPLEMENTATION_COMPLETE.md"
safe_delete "./AUTOMATED_DEPLOYMENT_PREPARATION_COMPLETE.md"
safe_delete "./BRONZE_TIER_COMPLETE.md"
safe_delete "./CEO_BRIEFING_COMPLETE.md"
safe_delete "./CORE_FEATURES_DEPLOYMENT_COMPLETE.md"
safe_delete "./DAILY_SUMMARY_2026-02-26.md"
safe_delete "./DAILY_SUMMARY_2026-02-27.md"
safe_delete "./DAILY_SUMMARY_2026-02-27_FINAL.md"
safe_delete "./DEPLOYMENT_COMPLETE.md"
safe_delete "./DEPLOYMENT_COMPLETE_SUMMARY.md"
safe_delete "./DEPLOYMENT_VERIFIED.md"
safe_delete "./DOCKERIZATION_COMPLETE.md"
safe_delete "./DOCKER_UPDATE_COMPLETE.md"
safe_delete "./ERROR_RECOVERY_IMPLEMENTATION_COMPLETE.md"
safe_delete "./FINAL_PRODUCTION_SUMMARY.md"
safe_delete "./FINAL_SESSION_SUMMARY_2026-02-27.md"
safe_delete "./FINAL_VERIFICATION.md"
safe_delete "./GOLD_TIER_COMPLETE_SUMMARY.md"
safe_delete "./GOLD_TIER_EXTENDED_SESSION_FINAL_REPORT.md"
safe_delete "./GOLD_TIER_PRODUCTION_READINESS_CHECKLIST.md"
safe_delete "./HACKATHON_COMPLIANCE_STATUS.md"
safe_delete "./HACKATHON_FINAL_STATUS.md"
safe_delete "./IMPLEMENTATION_COMPLETE.md"
safe_delete "./INTEGRATION_SETUP_COMPLETE.md"
safe_delete "./ODOO_IMPLEMENTATION_COMPLETE.md"
safe_delete "./PLATINUM_TIER_COMPLETE.md"
safe_delete "./PLATINUM_TIER_COMPLETE_SUMMARY.md"
safe_delete "./PLATINUM_TIER_FINAL_STATUS.md"
safe_delete "./PLATINUM_TIER_PHASE1_COMPLETE.md"
safe_delete "./PLATINUM_TIER_PHASE2_COMPLETE.md"
safe_delete "./PLATINUM_TIER_PHASE3_COMPLETE.md"
safe_delete "./PLATINUM_TIER_PHASE5_COMPLETE.md"
safe_delete "./PLATINUM_TIER_PHASES_1_2_3_SUMMARY.md"
safe_delete "./PLATINUM_TIER_PHASES_1_2_SUMMARY.md"
safe_delete "./PLATINUM_TIER_PLANNING_COMPLETE.md"
safe_delete "./QWEN_SYSTEM_COMPLETE.md"
safe_delete "./SESSION_COMPLETE.md"
safe_delete "./SESSION_SUMMARY_RALPH_TESTING_PREP.md"
safe_delete "./SILVER_TIER_COMPLETE.md"
safe_delete "./SOCIAL_MEDIA_IMPLEMENTATION_COMPLETE.md"
safe_delete "./SYSTEM_READY.md"
safe_delete "./VAULT_REORGANIZATION_COMPLETE.md"
echo ""

echo "🗑️  Removing duplicate and redundant documentation..."
safe_delete "./AI_EMPLOYEE_QUICK_START.md"
safe_delete "./DEMO_VIDEO_SCRIPT.md"
safe_delete "./EMAIL_AUTO_RESPONSE_WORKFLOW.md"
safe_delete "./EMAIL_WORKFLOW_DEMONSTRATION.md"
safe_delete "./FINAL_SUBMISSION_CHECKLIST.md"
safe_delete "./FINAL_SUBMISSION_PACKAGE.md"
safe_delete "./GET_STARTED_NOW.md"
safe_delete "./GOLD_TIER_PLAN.md"
safe_delete "./GOLD_TIER_QUICK_START.md"
safe_delete "./PLATINUM_TIER_CLOUD_IMPLEMENTATION_PLAN.md"
safe_delete "./PLATINUM_TIER_PLAN.md"
safe_delete "./PRACTICAL_USAGE_GUIDE.md"
safe_delete "./PRODUCTION_DEPLOYMENT_GUIDE.md"
safe_delete "./PRODUCTION_READY.md"
safe_delete "./QUICK_DEPLOYMENT_REFERENCE.md"
safe_delete "./QUICK_REFERENCE.md"
safe_delete "./QUICK_START.md"
safe_delete "./QUICK_START_NOW.md"
safe_delete "./QUICK_START_TESTING.md"
safe_delete "./RALPH_ASSESSMENT_AND_RECOMMENDATION.md"
safe_delete "./RALPH_GROQ_BATCH_DEMO.md"
safe_delete "./RALPH_GROQ_GUIDE.md"
safe_delete "./RALPH_GROQ_QUICK_START.md"
safe_delete "./RALPH_GROQ_SUCCESS.md"
safe_delete "./RALPH_GROQ_SUMMARY.md"
safe_delete "./RALPH_MANUAL_TEST_INSTRUCTIONS.md"
safe_delete "./RALPH_QUICK_TEST_REFERENCE.md"
safe_delete "./RALPH_TESTING_READINESS_SUMMARY.md"
safe_delete "./RALPH_TESTING_WALKTHROUGH.md"
safe_delete "./RALPH_TEST_EXECUTION_GUIDE.md"
safe_delete "./RALPH_TEST_RESULTS.md"
safe_delete "./RALPH_WIGGUM_COMPLETE.md"
safe_delete "./RALPH_WIGGUM_REFINED_GUIDE.md"
safe_delete "./RALPH_WIGGUM_REFINEMENT_COMPLETE.md"
safe_delete "./RALPH_WIGGUM_TESTING.md"
safe_delete "./RALPH_WIGGUM_WORKING_GUIDE.md"
safe_delete "./SILVER_TIER_PLAN.md"
safe_delete "./SILVER_TIER_SETUP.md"
safe_delete "./START_HERE_SUBMISSION.md"
safe_delete "./SUBMISSION_QUICK_REFERENCE.md"
safe_delete "./WORKFLOW_DEMONSTRATION.md"
echo ""

echo "🗑️  Removing Platinum Tier documentation (not implemented)..."
safe_delete "./PLATINUM_TIER_API_DOCUMENTATION.md"
safe_delete "./PLATINUM_TIER_ARCHITECTURE.md"
safe_delete "./PLATINUM_TIER_DEPLOYMENT_GUIDE.md"
safe_delete "./PLATINUM_TIER_USER_GUIDE.md"
safe_delete "./LIST_ALL_TOOLS.md"
safe_delete "./CLOUD_VM_SETUP.md"
echo ""

echo "=========================================="
echo "✅ Cleanup Complete!"
echo "=========================================="
echo ""
echo "Files backed up to: $BACKUP_DIR"
echo ""
echo "📋 Remaining Essential Files:"
echo ""
echo "Documentation:"
echo "  ✓ README.md"
echo "  ✓ Personal AI Employee Hackathon 0_ Building Autonomous FTEs in 2026.md"
echo "  ✓ HACKATHON_README.md"
echo "  ✓ HACKATHON_COMPLETE.md"
echo "  ✓ DEMO_VIDEO_GUIDE.md"
echo "  ✓ SUBMISSION_CHECKLIST.md"
echo "  ✓ PRIORITY_ACTIONS_COMPLETE.md"
echo "  ✓ START_HERE.md"
echo ""
echo "Setup Guides:"
echo "  ✓ GMAIL_SETUP.md"
echo "  ✓ DOCKERIZATION_GUIDE.md"
echo "  ✓ AUTOMATED_DEPLOYMENT_GUIDE.md"
echo "  ✓ GOLD_TIER_DEPLOYMENT_GUIDE.md"
echo "  ✓ ODOO_INSTALLATION_GUIDE.md"
echo "  ✓ SOCIAL_MEDIA_INSTALLATION_GUIDE.md"
echo "  ✓ LINKEDIN_SETUP_GUIDE.md"
echo "  ✓ TWITTER_SETUP_GUIDE.md"
echo ""
echo "Technical Docs:"
echo "  ✓ VAULT_WORKFLOW.md"
echo "  ✓ EMAIL_PROCESSING_FIX.md"
echo "  ✓ HYBRID_LLM_GUIDE.md"
echo "  ✓ GET_GROQ_API_KEY.md"
echo "  ✓ ODOO_LOGIN_CREDENTIALS.md"
echo ""
echo "Scripts:"
echo "  ✓ ralph_groq_setup.sh"
echo "  ✓ setup_cron.sh"
echo "  ✓ deploy_odoo.sh"
echo "  ✓ deploy_social_media.sh"
echo "  ✓ verify_deployment.sh"
echo "  ✓ check_system_status.sh"
echo "  ✓ stop_all_services.sh"
echo "  ✓ activate_env.sh"
echo ""
echo "Core Files:"
echo "  ✓ ralph_groq_orchestrator.py"
echo "  ✓ docker-compose.yml"
echo "  ✓ .env (your configuration)"
echo "  ✓ watchers/ (all watcher scripts)"
echo "  ✓ .claude/skills/ (all Agent Skills)"
echo ""
echo "To restore deleted files: cp $BACKUP_DIR/* ./"
echo ""
