#!/usr/bin/env python3
"""
Simple CEO Briefing Generator
Generates weekly business intelligence reports from existing data
"""

from pathlib import Path
from datetime import datetime, timedelta
import sys
import logging

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent))

from data_collectors.task_collector import TaskDataCollector
from data_collectors.communication_collector import CommunicationDataCollector
from data_collectors.financial_collector import FinancialDataCollector

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class SimpleCEOBriefingGenerator:
    def __init__(self, vault_path: str):
        self.vault = Path(vault_path)
        self.briefings = self.vault / 'Briefings'
        self.briefings.mkdir(exist_ok=True)

        self.task_collector = TaskDataCollector(vault_path)
        self.comm_collector = CommunicationDataCollector(vault_path)
        self.financial_collector = FinancialDataCollector(vault_path)

    def generate_weekly_briefing(self):
        """Generate weekly CEO briefing"""
        logger.info("Generating weekly CEO briefing...")

        # Calculate date range (last 7 days)
        end_date = datetime.now()
        start_date = end_date - timedelta(days=7)

        logger.info(f"Period: {start_date.date()} to {end_date.date()}")

        # Collect data
        task_data = self.task_collector.collect_weekly_data(start_date, end_date)
        comm_data = self.comm_collector.collect_weekly_data(start_date, end_date)
        financial_data = self.financial_collector.collect_weekly_data(start_date.date(), end_date.date())

        # Generate report
        report = self._format_report(start_date, end_date, task_data, comm_data, financial_data)

        # Save report
        filename = f"{end_date.strftime('%Y-%m-%d')}_Weekly_Briefing.md"
        filepath = self.briefings / filename
        filepath.write_text(report)

        logger.info(f"✅ CEO briefing saved to {filepath}")
        return filepath

    def _format_report(self, start_date, end_date, tasks, comm, financial):
        """Format the briefing report"""

        # Generate executive summary
        exec_summary = self._generate_executive_summary(tasks, comm, financial)

        # Format task list
        completed_list = self._format_task_list(tasks['completed']['tasks'])

        # Format bottlenecks
        bottlenecks_table = self._format_bottlenecks(tasks['bottlenecks']['tasks'])

        # Generate recommendations
        recommendations = self._generate_recommendations(tasks, comm, financial)

        # Format financial section
        financial_section = self._format_financial_section(financial)

        report = f"""# Weekly CEO Briefing

---
generated: {datetime.now().isoformat()}
period: {start_date.strftime('%Y-%m-%d')} to {end_date.strftime('%Y-%m-%d')}
---

## 📊 Executive Summary

{exec_summary}

{financial_section}

## ✅ Task Completion

### Completed This Week
**Total:** {tasks['completed']['count']} tasks

{completed_list}

### Pending Tasks
**Total:** {tasks['pending']['count']} tasks
**High Priority:** {len([t for t in tasks['pending']['tasks'] if t.get('priority') == 'high'])} tasks

## 🚨 Bottlenecks Identified

{bottlenecks_table}

## 📧 Communications

### Email Activity
- **Sent:** {comm['emails']['sent']} emails
- **Received:** {comm['emails']['received']} emails
- **Processed:** {comm['emails']['processed']} emails
- **Response Rate:** {comm['emails']['response_rate']}%

### Social Media
- **Posts Published:** {comm['social_media']['posts']}

### Approvals
- **Requested:** {comm['approvals']['requested']}
- **Granted:** {comm['approvals']['granted']}
- **Approval Rate:** {comm['approvals']['approval_rate']}%

## 💡 Proactive Recommendations

{recommendations}

## 📅 System Health

- **Tasks Completed:** {tasks['completed']['count']}
- **Tasks Pending:** {tasks['pending']['count']}
- **Bottlenecks:** {tasks['bottlenecks']['count']}
- **System Status:** {'⚠️ Attention Needed' if tasks['bottlenecks']['count'] > 0 else '✅ Healthy'}

## 🎯 Action Items for This Week

{self._generate_action_items(tasks, comm, financial)}

---

*Generated by AI Employee CEO Briefing System*
*Next briefing: {(end_date + timedelta(days=7)).strftime('%Y-%m-%d')}*
"""
        return report

    def _format_financial_section(self, financial):
        """Format financial data section"""
        if not financial.get('available'):
            return """## 💰 Financial Overview

*Financial data not available. Install and configure Odoo for financial reporting.*
"""

        pl = financial.get('profit_loss', {})
        cf = financial.get('cash_flow', {})
        balances = financial.get('balances', {})
        outstanding = financial.get('outstanding_invoices', {})

        return f"""## 💰 Financial Overview

### Profit & Loss (This Week)
- **Revenue:** ${pl.get('revenue', 0):,.2f}
- **Expenses:** ${pl.get('expenses', 0):,.2f}
- **Net Profit:** ${pl.get('net_profit', 0):,.2f}
- **Profit Margin:** {pl.get('profit_margin', 0):.1f}%

### Cash Flow (This Week)
- **Inflows:** ${cf.get('inflows', 0):,.2f}
- **Outflows:** ${cf.get('outflows', 0):,.2f}
- **Net Cash Flow:** ${cf.get('net_cash_flow', 0):,.2f}

### Current Balances
- **Cash Position:** ${balances.get('cash', 0):,.2f}
- **Accounts Receivable:** ${balances.get('receivables', 0):,.2f}
- **Accounts Payable:** ${balances.get('payables', 0):,.2f}
- **Working Capital:** ${balances.get('working_capital', 0):,.2f}

### Outstanding Invoices
- **Count:** {outstanding.get('count', 0)} invoices
- **Total Amount:** ${outstanding.get('total', 0):,.2f}
"""

    def _generate_executive_summary(self, tasks, comm, financial):
        """Generate 2-3 sentence executive summary"""
        completed = tasks['completed']['count']
        pending = tasks['pending']['count']
        bottlenecks = tasks['bottlenecks']['count']

        # Base summary on tasks
        if completed > 0 and bottlenecks == 0:
            summary = f"Productive week with {completed} tasks completed and no bottlenecks. Operations running smoothly."
        elif completed > 0 and bottlenecks > 0:
            summary = f"Good progress with {completed} tasks completed, but {bottlenecks} bottleneck(s) need attention. Review stuck tasks to maintain momentum."
        elif completed == 0 and bottlenecks > 0:
            summary = f"⚠️ Low productivity week with {bottlenecks} bottleneck(s) blocking progress. Immediate action required to unblock tasks."
        else:
            summary = f"Quiet week with {pending} pending tasks. Consider prioritizing high-value activities."

        # Add financial context if available
        if financial.get('available'):
            pl = financial.get('profit_loss', {})
            net_profit = pl.get('net_profit', 0)
            if net_profit > 0:
                summary += f" Financially strong with ${net_profit:,.2f} net profit this week."
            elif net_profit < 0:
                summary += f" ⚠️ Financial concern: ${abs(net_profit):,.2f} net loss this week."

        return summary

    def _format_task_list(self, tasks):
        """Format completed task list"""
        if not tasks:
            return "- No tasks completed this week"

        lines = []
        for task in tasks[:10]:  # Show top 10
            task_type = task.get('type', 'task')
            task_name = task['name']
            lines.append(f"- [{task_type}] {task_name}")

        if len(tasks) > 10:
            lines.append(f"- ... and {len(tasks) - 10} more")

        return "\n".join(lines)

    def _format_bottlenecks(self, bottlenecks):
        """Format bottleneck section"""
        if not bottlenecks:
            return "✅ No bottlenecks detected. All tasks progressing normally."

        lines = ["| Task | Age | Priority | Likely Cause |", "|------|-----|----------|--------------|"]
        for b in bottlenecks:
            lines.append(f"| {b['name']} | {b['age_days']} days | {b['priority']} | {b['likely_cause']} |")

        return "\n".join(lines)

    def _generate_recommendations(self, tasks, comm, financial):
        """Generate proactive recommendations"""
        recommendations = []
        rec_num = 1

        # Check for bottlenecks
        if tasks['bottlenecks']['count'] > 0:
            recommendations.append(
                f"{rec_num}. 🔴 **Unblock Tasks:** {tasks['bottlenecks']['count']} task(s) stuck for >3 days. Review and take action to unblock."
            )
            rec_num += 1

        # Financial recommendations
        if financial.get('available'):
            pl = financial.get('profit_loss', {})
            cf = financial.get('cash_flow', {})
            balances = financial.get('balances', {})
            outstanding = financial.get('outstanding_invoices', {})

            # Check for negative cash flow
            if cf.get('net_cash_flow', 0) < 0:
                recommendations.append(
                    f"{rec_num}. 💰 **Cash Flow Alert:** Negative cash flow of ${abs(cf.get('net_cash_flow', 0)):,.2f} this week. Review expenses and accelerate collections."
                )
                rec_num += 1

            # Check for low profit margin
            if pl.get('profit_margin', 0) < 10 and pl.get('revenue', 0) > 0:
                recommendations.append(
                    f"{rec_num}. 📊 **Profit Margin:** Only {pl.get('profit_margin', 0):.1f}% profit margin. Consider cost optimization or pricing review."
                )
                rec_num += 1

            # Check for outstanding invoices
            if outstanding.get('count', 0) > 5:
                recommendations.append(
                    f"{rec_num}. 💳 **Collections:** {outstanding.get('count', 0)} outstanding invoices totaling ${outstanding.get('total', 0):,.2f}. Prioritize collection efforts."
                )
                rec_num += 1

            # Check for low cash position
            if balances.get('cash', 0) < 10000:
                recommendations.append(
                    f"{rec_num}. 🏦 **Cash Position:** Cash balance is ${balances.get('cash', 0):,.2f}. Monitor closely and ensure sufficient reserves."
                )
                rec_num += 1

        # Check for low email response rate
        if comm['emails']['received'] > 0 and comm['emails']['response_rate'] < 50:
            recommendations.append(
                f"{rec_num}. 📧 **Email Response:** Response rate is {comm['emails']['response_rate']}%. Consider prioritizing email responses."
            )
            rec_num += 1

        # Check for pending tasks
        if tasks['pending']['count'] > 10:
            recommendations.append(
                f"{rec_num}. 📋 **Task Backlog:** {tasks['pending']['count']} pending tasks. Consider batch processing or delegation."
            )
            rec_num += 1

        # Check for low social media activity
        if comm['social_media']['posts'] < 3:
            recommendations.append(
                f"{rec_num}. 📱 **Social Media:** Only {comm['social_media']['posts']} post(s) this week. Target is 3-5 posts/week."
            )
            rec_num += 1

        if not recommendations:
            recommendations.append("✅ No specific recommendations at this time. Continue current operations.")

        return "\n".join(recommendations)

    def _generate_action_items(self, tasks, comm, financial):
        """Generate specific action items"""
        actions = []

        # High priority from bottlenecks
        if tasks['bottlenecks']['count'] > 0:
            actions.append(f"- [ ] Review and unblock {tasks['bottlenecks']['count']} stuck task(s)")

        # Financial action items
        if financial.get('available'):
            outstanding = financial.get('outstanding_invoices', {})
            cf = financial.get('cash_flow', {})
            balances = financial.get('balances', {})

            # Outstanding invoices
            if outstanding.get('count', 0) > 5:
                actions.append(f"- [ ] Follow up on {outstanding.get('count', 0)} outstanding invoices")

            # Negative cash flow
            if cf.get('net_cash_flow', 0) < 0:
                actions.append(f"- [ ] Review and reduce expenses to improve cash flow")

            # Low cash position
            if balances.get('cash', 0) < 10000:
                actions.append(f"- [ ] Review cash position and ensure adequate reserves")

        # Email follow-ups
        if comm['emails']['received'] > comm['emails']['sent']:
            actions.append(f"- [ ] Respond to pending emails ({comm['emails']['received'] - comm['emails']['sent']} outstanding)")

        # Social media
        if comm['social_media']['posts'] < 3:
            actions.append(f"- [ ] Create {3 - comm['social_media']['posts']} more social media post(s)")

        # General review
        actions.append("- [ ] Review weekly performance and plan next week's priorities")

        return "\n".join(actions)


def main():
    import argparse

    parser = argparse.ArgumentParser(description='Generate CEO Briefing')
    parser.add_argument(
        '--vault',
        default='/mnt/d/AI/Personal-AI-Employee/AI_Employee_Vault',
        help='Path to Obsidian vault'
    )

    args = parser.parse_args()

    generator = SimpleCEOBriefingGenerator(args.vault)
    briefing_path = generator.generate_weekly_briefing()

    print(f"\n✅ CEO Briefing generated successfully!")
    print(f"📄 Location: {briefing_path}")
    print(f"\nTo view:")
    print(f"  cat {briefing_path}")


if __name__ == '__main__':
    main()
